// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARbnyHm49Ho310hXWziyyBNIW9U1D7FAE',
    appId: '1:380970287726:web:8e8080446a4e580a2b1c7f',
    messagingSenderId: '380970287726',
    projectId: 'fa-clube-delivery',
    authDomain: 'fa-clube-delivery.firebaseapp.com',
    storageBucket: 'fa-clube-delivery.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg2EQ57xPPQCH4kzDiVVC8_h65Vo38T3k',
    appId: '1:380970287726:android:6547bf06d5c334ac2b1c7f',
    messagingSenderId: '380970287726',
    projectId: 'fa-clube-delivery',
    storageBucket: 'fa-clube-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQjALRfiTQ3_XAvfv11B-pVfZNaMfCk-I',
    appId: '1:380970287726:ios:37e36f7722156d232b1c7f',
    messagingSenderId: '380970287726',
    projectId: 'fa-clube-delivery',
    storageBucket: 'fa-clube-delivery.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQjALRfiTQ3_XAvfv11B-pVfZNaMfCk-I',
    appId: '1:380970287726:ios:37e36f7722156d232b1c7f',
    messagingSenderId: '380970287726',
    projectId: 'fa-clube-delivery',
    storageBucket: 'fa-clube-delivery.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARbnyHm49Ho310hXWziyyBNIW9U1D7FAE',
    appId: '1:380970287726:web:16af7086025c74422b1c7f',
    messagingSenderId: '380970287726',
    projectId: 'fa-clube-delivery',
    authDomain: 'fa-clube-delivery.firebaseapp.com',
    storageBucket: 'fa-clube-delivery.firebasestorage.app',
  );
}
